export const ActionTypes = {
    addComment: 'ADD_COMMENT',
    deleteComment: 'DELETE_COMMENT',
    editComment: 'EDIT_COMMENT',
    sortCommentsDecDate: 'SORT_COMMENTS_DEC_DATE',
    sortCommentsAscDate: 'SORT_COMMENTS_ASC_DATE',
    sortCommentsDecLike: 'SORT_COMMENTS_DEC_LIKE',
    sortCommentsAscLike: 'SORT_COMMENTS_ASC_LIKE',
    addArticle: 'ADD_ARTICLE',
    editArticle: 'EDIT_ARTICLE',
    changeCommentCount: 'ADD_COMMENT_COUNT',
    sortArticlesDecDate: 'SORT_ARTICLES_DEC_DATE',
    sortArticlesAscDate: 'SORT_ARTICLES_ASC_DATE',
    sortArticlesDecLike: 'SORT_ARTICLES_DEC_LIKE',
    sortArticlesAscLike: 'SORT_ARTICLES_ASC_LIKE',
}